name: Python application Production

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Django
        run: | 
          python -c "import django; print(django.__version__)"
          python manage.py check
      
      - name: Unit Tests
        run: |
          python manage.py test
      
      - name: Code Analysis
        run: |
          pylint --disable=C,R,W --enable=E api/
      
      - name: Code Coverage
        run: |
          coverage run manage.py test
          coverage report
      
      - name: Build & Push Docker Image
        run: |
          docker build -t devsu-demo-python:${{github.sha }} .
          docker tag devsu-demo-python:${{github.sha }} 
          devsu-demo-python:latest
          docker push devsu-demo-python:${{github.sha }}
          docker push devsu-demo-python:latest
