name: Python application Production

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.3'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Django
        run: | 
          python -c "import django; print(django.__version__)"
          python manage.py check
      
      - name: Unit Tests
        run: |
          python manage.py test
      
      - name: Code Analysis
        run: |
          pylint --fail-under=5 --disable=C,R,W,E1101,E0307 api/
      
      - name: Code Coverage
        run: |
          coverage run manage.py test
          coverage report
      
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1
      
      - name: Build & Push Docker Image
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_USERNAME }}/devsu-demo-python
        run: |
          docker build -t $DOCKER_REPO:${{ github.sha }} .
          docker tag $DOCKER_REPO:${{ github.sha }} $DOCKER_REPO:latest
          docker push $DOCKER_REPO:${{ github.sha }}
          docker push $DOCKER_REPO:latest
      
      - name: Deployment Info
        run: |
          echo "Para desplegar en tu Kubernetes local:"
          echo "1. Descarga la última imagen: docker pull ${{ secrets.DOCKER_USERNAME }}/devsu-demo-python:latest"
          echo "2. Aplica las configuraciones: kubectl apply -f k8s/"
